# Generated by Django 5.2.4 on 2025-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_groups_userdetails_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='agent',
            field=models.CharField(choices=[('Are you an agent?', ''), ('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
    ]
