# Generated by Django 5.2.4 on 2025-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdetails_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='agent',
            field=models.CharField(choices=[('', 'Are you an agent?'), ('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
    ]
