# Generated by Django 5.2.4 on 2025-07-18 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image1', models.ImageField(upload_to='image/')),
                ('image2', models.ImageField(upload_to='image/')),
                ('image3', models.ImageField(upload_to='image/')),
                ('video_file', models.FileField(upload_to='property_videos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(verbose_name='text_duration in seconds')),
                ('property_address', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
