# Generated by Django 5.2.4 on 2025-07-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_alter_propertie_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('apartment_type', models.CharField(choices=[('studio', 'Studio'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('5_bedroom', '5 Bedroom'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('condo', 'Condo'), ('cottage', 'Cottage'), ('bungalow', 'Bungalow'), ('loft', 'Loft'), ('other', 'Other')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image1', models.ImageField(upload_to='image/')),
                ('image2', models.ImageField(upload_to='image/')),
                ('image3', models.ImageField(upload_to='image/')),
                ('video_file', models.FileField(upload_to='property_videos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(verbose_name='text_duration in seconds')),
                ('property_address', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Propertie',
        ),
    ]
